const currencies={GBP:{symbol:'£',rate:1},USD:{symbol:'$',rate:1.29},EUR:{symbol:'€',rate:1.18},INR:{symbol:'₹',rate:108.4},JPY:{symbol:'¥',rate:191.2},CAD:{symbol:'C$',rate:1.76},AUD:{symbol:'A$',rate:1.96},GEL:{symbol:'₾',rate:3.5122}};
const categories={Food:['🍜','#d97941'],Transport:['🚕','#557c6d'],Shopping:['🛍️','#a26476'],Bills:['💡','#c4a14b'],Health:['💊','#5985a6'],Entertainment:['🎬','#735f92'],Travel:['✈️','#4b8b94'],Other:['◌','#7b827e']};
const today=new Date(); const iso=d=>d.toISOString().slice(0,10); const shift=n=>{const d=new Date(today);d.setDate(d.getDate()+n);return iso(d)};
const seed={activeUser:'u1',users:[{id:'u1',name:'Neera Patel',email:'neera@example.com',currency:'GBP',budget:2200,color:'#1d654f'},{id:'u2',name:'Arjun Patel',email:'arjun@example.com',currency:'USD',budget:3000,color:'#735f92'}],expenses:[
 {id:'e1',userId:'u1',merchant:'Borough Market',amount:28.5,currency:'GBP',category:'Food',date:shift(0),note:'Lunch & groceries'},
 {id:'e2',userId:'u1',merchant:'TfL Travel',amount:8.2,currency:'GBP',category:'Transport',date:shift(0),note:'Daily commute'},
 {id:'e3',userId:'u1',merchant:'Muji',amount:42,currency:'EUR',category:'Shopping',date:shift(-1),note:'Home supplies'},
 {id:'e4',userId:'u1',merchant:'Octopus Energy',amount:86.3,currency:'GBP',category:'Bills',date:shift(-2),note:'Electricity'},
 {id:'e5',userId:'u1',merchant:'Cafe Nero',amount:6.4,currency:'GBP',category:'Food',date:shift(-3),note:'Coffee'},
 {id:'e6',userId:'u2',merchant:'Whole Foods',amount:62.1,currency:'USD',category:'Food',date:shift(0),note:'Weekly groceries'}]};
let state={activeUser:localStorage.getItem('daybook-active-user'),users:[],expenses:[]}; let modal=null;let range='month';let activeView='overview';let txSearch='';let reportFrom=shift(-30),reportTo=iso(today);
const api=async(path,options={})=>{const response=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||'Request failed')}return response.status===204?null:response.json()};
const save=()=>localStorage.setItem('daybook-active-user',state.activeUser||'');
const user=()=>state.users.find(u=>u.id===state.activeUser)||state.users[0];
const gbp=(amount,currency)=>amount/currencies[currency].rate; const convert=(amount,from,to)=>gbp(amount,from)*currencies[to].rate;
const money=(amount,currency=user().currency)=>currency==='GEL'
  ? `${currencies.GEL.symbol}${new Intl.NumberFormat(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}).format(amount)}`
  : new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:currency==='JPY'?0:2}).format(amount);
const userExpenses=()=>state.expenses.filter(e=>e.userId===user().id).sort((a,b)=>b.date.localeCompare(a.date));
const monthExpenses=()=>userExpenses().filter(e=>e.date.slice(0,7)===iso(today).slice(0,7));
const total=xs=>xs.reduce((s,e)=>s+convert(e.amount,e.currency,user().currency),0);
const escape=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(){if(!state.users.length){document.querySelector('#app').innerHTML='<div class="empty" style="padding-top:20vh">No users found. Import <b>schema.sql</b>, then refresh.</div>';return}const u=user();document.querySelector('#app').innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">↗</span>daybook</div><nav class="nav">${navButton('overview','⌂','Overview')}${navButton('transactions','↗','Transactions')}${navButton('budgets','◎','Budgets')}${navButton('reports','◫','Reports')}</nav><div class="sidebar-foot"><div class="user-card" data-action="users"><div class="avatar" style="background:${u.color}">${initials(u.name)}</div><div class="user-meta"><strong>${escape(u.name)}</strong><span>${currencies[u.currency]?.symbol||u.currency} account</span></div><span>⌃</span></div></div></aside><main class="main"><header class="topbar"><div><div class="eyebrow">${today.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</div><h1 class="title">${viewTitle()}</h1></div><div class="top-actions"><button class="btn" data-action="users">Switch user</button><button class="btn primary" data-action="expense">＋ Add expense</button></div></header>${viewContent()}</main></div><nav class="mobile-nav">${navButton('overview','⌂','')}${navButton('transactions','↗','')}<button data-action="expense">⊕</button>${navButton('budgets','◎','')}${navButton('reports','◫','')}</nav>${modalMarkup()}`;bind()}
const navButton=(view,icon,label)=>`<button data-view="${view}" class="${activeView===view?'active':''}" aria-label="${view}"><span class="nav-icon">${navIcon(view)}</span><span class="nav-label">${label||view[0].toUpperCase()+view.slice(1)}</span></button>`;
function navIcon(view){const icons={
  overview:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 13V5.8C4 4.8 4.8 4 5.8 4H9v9H4Zm0 5.2V16h5v4H5.8A1.8 1.8 0 0 1 4 18.2ZM12 20v-7h8v5.2a1.8 1.8 0 0 1-1.8 1.8H12Zm0-10V4h6.2A1.8 1.8 0 0 1 20 5.8V10h-8Z"/></svg>',
  transactions:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 8h13m-3-3 3 3-3 3M19 16H6m3 3-3-3 3-3"/></svg>',
  budgets:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h15.5v11H5.8A1.8 1.8 0 0 1 4 16.7V7.5Zm0 0V6.3A2.3 2.3 0 0 1 6.3 4h10.2v3.5M15 11h6v4h-6a2 2 0 0 1 0-4Z"/></svg>',
  reports:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19V9m5 10V5m5 14v-6m5 6V8"/></svg>'
};return icons[view]||''}
const viewTitle=()=>({overview:`Good ${greeting()}, ${escape(user().name.split(' ')[0])}.`,transactions:'Transactions',budgets:'Monthly budget',reports:'Spending reports'})[activeView];
function viewContent(){if(activeView==='transactions')return transactionsView();if(activeView==='budgets')return budgetsView();if(activeView==='reports')return reportsView();const u=user(),xs=monthExpenses(),monthTotal=total(xs),daily=total(xs.filter(e=>e.date===iso(today))),pct=Math.min(100,monthTotal/u.budget*100||0);return `<section class="stats"><article class="stat"><div class="stat-label">SPENT THIS MONTH <span class="pill">${xs.length} entries</span></div><div class="stat-value">${money(monthTotal)}</div><div class="stat-note">Converted to ${u.currency}</div></article><article class="stat"><div class="stat-label">TODAY</div><div class="stat-value">${money(daily)}</div><div class="stat-note">${xs.filter(e=>e.date===iso(today)).length} transactions today</div></article><article class="stat"><div class="stat-label">MONTHLY BUDGET <span class="pill warm">${pct.toFixed(0)}% used</span></div><div class="progress"><span style="width:${pct}%"></span></div><div class="stat-value" style="font-size:21px">${money(Math.max(0,u.budget-monthTotal))} left</div><div class="stat-note">of ${money(u.budget)}</div></article></section><div class="content-grid"><div><section class="panel"><div class="panel-head"><h2>Spending rhythm</h2><select class="select" id="range"><option value="week" ${range==='week'?'selected':''}>Last 7 days</option><option value="month" ${range==='month'?'selected':''}>This month</option></select></div>${chart()}</section><div class="section-head"><h2>Recent activity</h2></div><section class="panel">${transactions(userExpenses().slice(0,7))}</section></div><aside class="panel"><div class="panel-head"><h2>By category</h2></div>${categoryBreakdown(xs)}</aside></div>`}
function transactionsView(){const xs=userExpenses().filter(e=>(e.merchant+' '+(e.note||'')+' '+e.category).toLowerCase().includes(txSearch.toLowerCase()));return `<section class="panel"><div class="page-tools"><input class="input" id="tx-search" value="${escape(txSearch)}" placeholder="Search merchant, note or category"><span class="eyebrow">${xs.length} transactions</span></div><div id="tx-list">${transactions(xs,true)}</div></section>`}
function budgetsView(){const spent=total(monthExpenses()),u=user(),pct=Math.min(100,spent/u.budget*100||0);return `<div class="settings-grid"><section class="panel"><h2>Budget progress</h2><div class="stat-value">${money(spent)}</div><div class="progress big"><span style="width:${pct}%"></span></div><p class="stat-note">${pct.toFixed(1)}% of ${money(u.budget)} used · ${money(Math.max(0,u.budget-spent))} remaining</p></section><form class="panel" id="budget-form"><h2>Budget settings</h2><p class="modal-sub">Choose the currency used throughout your dashboard.</p><div class="field"><label>MONTHLY LIMIT</label><input name="budget" type="number" min="0" step="0.01" required value="${u.budget}"></div><div class="field"><label>BASE CURRENCY</label><select name="currency">${Object.keys(currencies).map(c=>`<option ${c===u.currency?'selected':''}>${c}</option>`).join('')}</select></div><button class="btn primary save-budget">Save settings</button></form></div>`}
function reportsView(){const xs=userExpenses().filter(e=>e.date>=reportFrom&&e.date<=reportTo),sum=total(xs),avg=xs.length?sum/xs.length:0;return `<div class="page-tools"><div class="filters"><input class="input" id="report-from" type="date" value="${reportFrom}"><input class="input" id="report-to" type="date" value="${reportTo}"></div><button class="btn" id="export-csv">Export CSV</button></div><section class="stats"><article class="stat"><div class="stat-label">TOTAL SPEND</div><div class="stat-value">${money(sum)}</div></article><article class="stat"><div class="stat-label">TRANSACTIONS</div><div class="stat-value">${xs.length}</div></article><article class="stat"><div class="stat-label">AVERAGE EXPENSE</div><div class="stat-value">${money(avg)}</div></article></section><div class="content-grid"><section class="panel"><div class="panel-head"><h2>Transactions in period</h2></div>${transactions(xs)}</section><aside class="panel"><div class="panel-head"><h2>Category summary</h2></div>${categoryBreakdown(xs)}</aside></div>`}
function chart(){let days=[];const n=range==='week'?7:Math.max(1,today.getDate());for(let i=n-1;i>=0;i--){const d=new Date(today);d.setDate(d.getDate()-i);const key=iso(d),v=total(userExpenses().filter(e=>e.date===key));days.push({d,v,key})}const max=Math.max(...days.map(x=>x.v),1);return `<div class="chart">${days.map((x,i)=>`<div class="bar-wrap" title="${money(x.v)}"><div class="bar ${x.key===iso(today)?'today':''}" style="height:${Math.max(2,x.v/max*145)}px"></div><span class="bar-label">${(range==='week'||i%4===0||i===days.length-1)?new Date(x.key+'T12:00').toLocaleDateString(undefined,{day:'numeric',weekday:range==='week'?'short':undefined}):''}</span></div>`).join('')}</div>`}
function transactions(xs,editable=false){if(!xs.length)return `<div class="empty">No expenses found.</div>`;return xs.map(e=>{const converted=convert(e.amount,e.currency,user().currency);return `<div class="transaction"><div class="cat-icon">${categories[e.category]?.[0]||'◌'}</div><div class="tx-main"><strong>${escape(e.merchant)}</strong><span>${e.category} · ${new Date(e.date+'T12:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}${e.note?' · '+escape(e.note):''}</span></div><div class="amount">−${money(converted)}${e.currency!==user().currency?`<small>${money(e.amount,e.currency)}</small>`:''}${editable?`<button class="row-delete" data-expense-delete="${e.id}">Delete</button>`:''}</div></div>`}).join('')}
function categoryBreakdown(xs){const sums=Object.fromEntries(Object.keys(categories).map(c=>[c,total(xs.filter(e=>e.category===c))]));const max=Math.max(...Object.values(sums),1);const rows=Object.entries(sums).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]);return rows.length?rows.map(([c,v])=>`<div class="category"><div class="cat-icon">${categories[c][0]}</div><div><strong>${c}</strong><div class="mini-progress"><span style="width:${v/max*100}%;background:${categories[c][1]}"></span></div></div><div class="category-amount">${money(v)}</div></div>`).join(''):`<div class="empty">Category insights will appear here.</div>`}
function modalMarkup(){if(modal==='expense')return `<div class="modal-backdrop"><form class="modal" id="expense-form"><h2>Add an expense</h2><p class="modal-sub">Record it in the currency you paid. Daybook handles the conversion.</p><div class="form-grid"><div class="field full"><label>MERCHANT OR DESCRIPTION</label><input name="merchant" required autofocus placeholder="e.g. Corner shop"></div><div class="field"><label>AMOUNT</label><input name="amount" required min="0.01" step="0.01" type="number" placeholder="0.00"></div><div class="field"><label>CURRENCY</label><select name="currency">${Object.keys(currencies).map(c=>`<option ${c===user().currency?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>CATEGORY</label><select name="category">${Object.keys(categories).map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field"><label>DATE</label><input name="date" type="date" required value="${iso(today)}"></div><div class="field full"><label>NOTE (OPTIONAL)</label><input name="note" placeholder="What was this for?"></div></div><div class="modal-actions"><button type="button" class="btn" data-action="close">Cancel</button><button class="btn primary">Save expense</button></div></form></div>`;
if(modal==='users')return `<div class="modal-backdrop"><div class="modal"><h2>Household profiles</h2><p class="modal-sub">Each person has private expenses, budgets and a preferred currency.</p><div class="users-list">${state.users.map(u=>`<div class="user-option ${u.id===state.activeUser?'active':''}" data-user="${u.id}"><div class="avatar" style="background:${u.color}">${initials(u.name)}</div><div class="user-meta"><strong>${escape(u.name)}</strong><span>${u.email} · ${u.currency}</span></div></div>`).join('')}</div><form id="user-form"><div class="form-grid"><div class="field full"><label>ADD ANOTHER PERSON</label><input name="name" required placeholder="Full name"></div><div class="field"><input name="email" required type="email" placeholder="Email"></div><div class="field"><select name="currency">${Object.keys(currencies).map(c=>`<option>${c}</option>`).join('')}</select></div></div><div class="modal-actions"><button type="button" class="btn" data-action="close">Close</button><button class="btn primary">Add person</button></div></form></div></div>`;return ''}
function bind(){document.querySelectorAll('[data-action="expense"]').forEach(b=>b.onclick=()=>{modal='expense';render()});document.querySelectorAll('[data-action="users"]').forEach(b=>b.onclick=()=>{modal='users';render()});document.querySelectorAll('[data-action="close"]').forEach(b=>b.onclick=()=>{modal=null;render()});document.querySelectorAll('[data-user]').forEach(b=>b.onclick=async e=>{if(e.target.dataset.delete)return;state.activeUser=b.dataset.user;save();state.expenses=await api('/expenses?userId='+encodeURIComponent(state.activeUser));modal=null;render()});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async e=>{e.stopPropagation();const id=b.dataset.delete;if(state.users.length===1)return;try{await api('/users/'+id,{method:'DELETE'});state.users=state.users.filter(u=>u.id!==id);if(state.activeUser===id){state.activeUser=state.users[0].id;state.expenses=await api('/expenses?userId='+encodeURIComponent(state.activeUser))}save();render()}catch(err){toast(err.message)}});document.querySelector('#range')?.addEventListener('change',e=>{range=e.target.value;render()});document.querySelector('#category-filter')?.addEventListener('change',e=>{const xs=e.target.value==='all'?userExpenses().slice(0,7):userExpenses().filter(x=>x.category===e.target.value).slice(0,7);document.querySelector('#transactions').innerHTML=transactions(xs)});document.querySelector('#expense-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{const row=await api('/expenses',{method:'POST',body:JSON.stringify({userId:user().id,merchant:f.get('merchant'),amount:Number(f.get('amount')),currency:f.get('currency'),category:f.get('category'),date:f.get('date'),note:f.get('note')})});state.expenses.unshift(row);modal=null;render();toast('Expense added')}catch(err){toast(err.message)}});document.querySelector('#user-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{const row=await api('/users',{method:'POST',body:JSON.stringify({name:f.get('name'),email:f.get('email'),currency:f.get('currency'),color:['#1d654f','#735f92','#a84b42','#4b8b94'][state.users.length%4]})});state.users.push(row);state.activeUser=row.id;state.expenses=[];save();modal=null;render();toast('Profile created')}catch(err){toast(err.message)}});document.querySelectorAll('.modal-backdrop').forEach(x=>x.onclick=e=>{if(e.target===x){modal=null;render()}})}
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();const greeting=()=>today.getHours()<12?'morning':today.getHours()<18?'afternoon':'evening';function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.append(el);setTimeout(()=>el.remove(),2600)}
document.addEventListener('click',async e=>{const view=e.target.closest('[data-view]');if(view){activeView=view.dataset.view;render();return}const del=e.target.closest('[data-expense-delete]');if(del){if(!confirm('Delete this expense?'))return;try{await api('/expenses/'+del.dataset.expenseDelete,{method:'DELETE'});state.expenses=state.expenses.filter(x=>x.id!==del.dataset.expenseDelete);render();toast('Expense deleted')}catch(err){toast(err.message)}return}if(e.target.closest('#export-csv'))exportCsv()});
document.addEventListener('input',e=>{if(e.target.id==='tx-search'){txSearch=e.target.value;const xs=userExpenses().filter(x=>(x.merchant+' '+(x.note||'')+' '+x.category).toLowerCase().includes(txSearch.toLowerCase()));document.querySelector('#tx-list').innerHTML=transactions(xs,true)}});
document.addEventListener('change',e=>{if(e.target.id==='report-from'){reportFrom=e.target.value;render()}if(e.target.id==='report-to'){reportTo=e.target.value;render()}});
document.addEventListener('submit',async e=>{if(e.target.id!=='budget-form')return;e.preventDefault();const f=new FormData(e.target);try{const updated=await api('/users/'+user().id,{method:'PATCH',body:JSON.stringify({budget:Number(f.get('budget')),currency:f.get('currency')})});Object.assign(user(),updated);render();toast('Budget settings saved')}catch(err){toast(err.message)}});
function exportCsv(){const xs=userExpenses().filter(e=>e.date>=reportFrom&&e.date<=reportTo),q=v=>'"'+String(v??'').replaceAll('"','""')+'"',rows=[['Date','Merchant','Category','Amount','Currency','Note'],...xs.map(e=>[e.date,e.merchant,e.category,e.amount,e.currency,e.note||''])],blob=new Blob([rows.map(r=>r.map(q).join(',')).join('\n')],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`daybook-${reportFrom}-${reportTo}.csv`;a.click();URL.revokeObjectURL(url)}
async function bootstrap(){document.querySelector('#app').innerHTML='<div class="empty" style="padding-top:20vh">Loading Daybook…</div>';try{state.users=await api('/users');if(!state.users.length){render();return}if(!state.users.some(u=>u.id===state.activeUser))state.activeUser=state.users[0].id;save();state.expenses=await api('/expenses?userId='+encodeURIComponent(state.activeUser));render()}catch(err){document.querySelector('#app').innerHTML=`<div class="empty" style="padding-top:20vh"><b>Could not connect to Daybook.</b><br><br>${escape(err.message)}</div>`}}bootstrap();
