const currencies={GBP:{symbol:'£',rate:1},USD:{symbol:'$',rate:1.29},EUR:{symbol:'€',rate:1.18},INR:{symbol:'₹',rate:108.4},JPY:{symbol:'¥',rate:191.2},CAD:{symbol:'C$',rate:1.76},AUD:{symbol:'A$',rate:1.96},GEL:{symbol:'₾',rate:3.5122}};
const categories={
  Groceries:['🛒','#5f8a62'], 'Dining Out':['🍽️','#d97941'], 'House Rent':['🏠','#8a6d5c'],
  'Electricity Bill':['⚡','#c4a14b'], 'Mobile Bill':['📱','#6f86a0'],
  'Internet Bill':['🌐','#4f8290'], 'Cab Charges':['🚕','#557c6d'],
  'Bus Ticket':['🚌','#638274'], 'Train Ticket':['🚆','#5d7185'],
  Shopping:['🛍️','#a26476'], Health:['💊','#5985a6'], Insurance:['🛡️','#667c99'],
  'Personal Care':['✂️','#9b7294'],
  Subscriptions:['🔁','#6e76a8'], Entertainment:['🎬','#735f92'], Travel:['✈️','#4b8b94'],
  'Gifts & Donations':['🎁','#b06d73'], Taxes:['🧾','#7a6f65'],
  'Hand Loan':['🤝','#9b6b58'], 'Debt Payments':['💳','#a05d5d'], 'Fees & Charges':['🏦','#797f87'],
  Food:['🍜','#d97941'], Other:['◌','#7b827e']
};
const today=new Date(); const iso=d=>d.toISOString().slice(0,10); const shift=n=>{const d=new Date(today);d.setDate(d.getDate()+n);return iso(d)};
const seed={activeUser:'u1',users:[{id:'u1',name:'Neera Patel',email:'neera@example.com',currency:'GBP',budget:2200,color:'#1d654f'},{id:'u2',name:'Arjun Patel',email:'arjun@example.com',currency:'USD',budget:3000,color:'#735f92'}],expenses:[
 {id:'e1',userId:'u1',merchant:'Borough Market',amount:28.5,currency:'GBP',category:'Food',date:shift(0),note:'Lunch & groceries'},
 {id:'e2',userId:'u1',merchant:'TfL Travel',amount:8.2,currency:'GBP',category:'Transport',date:shift(0),note:'Daily commute'},
 {id:'e3',userId:'u1',merchant:'Muji',amount:42,currency:'EUR',category:'Shopping',date:shift(-1),note:'Home supplies'},
 {id:'e4',userId:'u1',merchant:'Octopus Energy',amount:86.3,currency:'GBP',category:'Bills',date:shift(-2),note:'Electricity'},
 {id:'e5',userId:'u1',merchant:'Cafe Nero',amount:6.4,currency:'GBP',category:'Food',date:shift(-3),note:'Coffee'},
 {id:'e6',userId:'u2',merchant:'Whole Foods',amount:62.1,currency:'USD',category:'Food',date:shift(0),note:'Weekly groceries'}]};
let state={activeUser:localStorage.getItem('daybook-active-user'),users:[],expenses:[],income:[],limits:[],ledger:[]}; let modal=null;let range='month';let activeView='overview';let txSearch='';let reportFrom=shift(-30),reportTo=iso(today);
const api=async(path,options={})=>{const response=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options});if(!response.ok){const body=await response.json().catch(()=>({}));const error=new Error(body.error||'Request failed');error.status=response.status;throw error}return response.status===204?null:response.json()};
const save=()=>localStorage.setItem('daybook-active-user',state.activeUser||'');
const user=()=>state.users.find(u=>u.id===state.activeUser)||state.users[0];
const gbp=(amount,currency)=>amount/currencies[currency].rate; const convert=(amount,from,to)=>gbp(amount,from)*currencies[to].rate;
const money=(amount,currency=user().currency)=>currency==='GEL'
  ? `${currencies.GEL.symbol}${new Intl.NumberFormat(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}).format(amount)}`
  : new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:currency==='JPY'?0:2}).format(amount);
const userExpenses=()=>state.expenses.filter(e=>e.userId===user().id).sort((a,b)=>b.date.localeCompare(a.date));
const monthExpenses=()=>userExpenses().filter(e=>e.date.slice(0,7)===iso(today).slice(0,7));
const total=xs=>xs.reduce((s,e)=>s+convert(e.amount,e.currency,user().currency),0);
const currencyMoney=(amount,currency)=>new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:currency==='JPY'?0:2}).format(amount);
const balances=()=>Object.keys(currencies).map(currency=>({currency,income:state.income.filter(x=>x.currency===currency).reduce((s,x)=>s+Number(x.amount),0),spent:state.expenses.filter(x=>x.currency===currency).reduce((s,x)=>s+Number(x.amount),0)})).map(x=>({...x,balance:x.income-x.spent})).filter(x=>x.income||x.spent);
const ledgerRows=()=>state.ledger.filter(x=>(x.description+' '+(x.note||'')+' '+x.currency+' '+x.type).toLowerCase().includes(txSearch.toLowerCase()));
const escape=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(){if(!state.users.length){showAuth();return}const u=user();document.querySelector('#app').innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">↗</span>daybook</div><nav class="nav">${navButton('overview','⌂','Overview')}${navButton('transactions','↗','Transactions')}${navButton('budgets','◎','Limits')}${navButton('reports','◫','Reports')}</nav><div class="sidebar-foot"><div class="user-card"><div class="avatar" style="background:${u.color}">${initials(u.name)}</div><div class="user-meta"><strong>${escape(u.name)}</strong><span>${escape(u.email)}</span></div></div></div></aside><main class="main"><header class="topbar"><div><div class="eyebrow">${today.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</div><h1 class="title">${viewTitle()}</h1></div><div class="top-actions"><button class="btn logout-btn" data-action="logout" aria-label="Sign out"><span class="logout-label">Sign out</span><span class="logout-icon" aria-hidden="true">↪</span></button><button class="btn" data-action="income">＋ Add income</button><button class="btn primary" data-action="expense">＋ Add expense</button></div></header>${viewContent()}</main></div><nav class="mobile-nav">${navButton('overview','⌂','')}${navButton('transactions','↗','')}<button data-action="expense">⊕</button>${navButton('budgets','◎','')}${navButton('reports','◫','')}</nav>${modalMarkup()}`;bind()}
const navButton=(view,icon,label)=>`<button data-view="${view}" class="${activeView===view?'active':''}" aria-label="${view==='budgets'?'Limits':view}"><span class="nav-icon">${navIcon(view)}</span><span class="nav-label">${label||({budgets:'Limits'}[view]||view[0].toUpperCase()+view.slice(1))}</span></button>`;
function navIcon(view){const icons={
  overview:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 13V5.8C4 4.8 4.8 4 5.8 4H9v9H4Zm0 5.2V16h5v4H5.8A1.8 1.8 0 0 1 4 18.2ZM12 20v-7h8v5.2a1.8 1.8 0 0 1-1.8 1.8H12Zm0-10V4h6.2A1.8 1.8 0 0 1 20 5.8V10h-8Z"/></svg>',
  transactions:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 8h13m-3-3 3 3-3 3M19 16H6m3 3-3-3 3-3"/></svg>',
  budgets:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h15.5v11H5.8A1.8 1.8 0 0 1 4 16.7V7.5Zm0 0V6.3A2.3 2.3 0 0 1 6.3 4h10.2v3.5M15 11h6v4h-6a2 2 0 0 1 0-4Z"/></svg>',
  reports:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19V9m5 10V5m5 14v-6m5 6V8"/></svg>'
};return icons[view]||''}
const viewTitle=()=>({overview:`Good ${greeting()}, ${escape(user().name.split(' ')[0])}.`,transactions:'Transaction history',budgets:'Monthly spending limits',reports:'Spending reports'})[activeView];
function viewContent(){if(activeView==='transactions')return transactionsView();if(activeView==='budgets')return budgetsView();if(activeView==='reports')return reportsView();const rows=balances(),xs=monthExpenses();return `<section class="stats balance-grid">${rows.length?rows.map(x=>`<article class="stat"><div class="stat-label">${x.currency} BALANCE</div><div class="stat-value">${currencyMoney(x.balance,x.currency)}</div><div class="stat-note">${currencyMoney(x.income,x.currency)} income · ${currencyMoney(x.spent,x.currency)} spent</div></article>`).join(''):'<article class="stat"><div class="empty">Add income to establish your first currency balance.</div></article>'}</section><div class="content-grid"><div><section class="panel"><div class="panel-head"><h2>Spending rhythm</h2><select class="select" id="range"><option value="week" ${range==='week'?'selected':''}>Last 7 days</option><option value="month" ${range==='month'?'selected':''}>This month</option></select></div>${chart()}</section><div class="section-head"><h2>Recent activity</h2></div><section class="panel">${ledgerMarkup(state.ledger.slice(0,7))}</section></div><aside class="panel"><div class="panel-head"><h2>Spending by category</h2></div>${categoryChart(xs)}</aside></div>`}
function transactionsView(){const xs=ledgerRows();return `<section class="panel"><div class="page-tools"><input class="input" id="tx-search" value="${escape(txSearch)}" placeholder="Search income, expense or currency"><span class="eyebrow">${xs.length} transactions</span></div><div id="tx-list">${ledgerMarkup(xs,true)}</div></section>`}
function budgetsView(){return `<div class="settings-grid"><section class="panel"><h2>Current limits</h2>${state.limits.length?state.limits.map(l=>{const spent=monthExpenses().filter(x=>x.currency===l.currency).reduce((s,x)=>s+Number(x.amount),0),pct=Math.min(100,spent/Number(l.monthlyLimit)*100||0);return `<div class="category"><div><strong>${l.currency}</strong><div class="mini-progress"><span style="width:${pct}%"></span></div></div><div class="category-amount">${currencyMoney(spent,l.currency)} / ${currencyMoney(l.monthlyLimit,l.currency)}</div></div>`}).join(''):'<div class="empty">No monthly spending limits set.</div>'}</section><form class="panel" id="limit-form"><h2>Set a monthly limit</h2><p class="modal-sub">Limits do not change your balance and are tracked separately per currency.</p><div class="field"><label>CURRENCY</label><select name="currency">${Object.keys(currencies).map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field"><label>MONTHLY LIMIT</label><input name="monthlyLimit" type="number" min="0" step="0.01" required></div><button class="btn primary save-budget">Save limit</button></form></div>`}
function reportsView(){const xs=userExpenses().filter(e=>e.date>=reportFrom&&e.date<=reportTo),summaries=Object.keys(currencies).map(currency=>{const rows=xs.filter(e=>e.currency===currency),sum=rows.reduce((s,e)=>s+Number(e.amount),0);return{currency,count:rows.length,sum,average:rows.length?sum/rows.length:0}}).filter(x=>x.count),reportRows=xs.map(e=>({id:e.id,type:'expense',description:e.merchant,amount:e.amount,currency:e.currency,date:e.date,note:e.note}));return `<div class="page-tools"><div class="filters"><input class="input" id="report-from" type="date" value="${reportFrom}"><input class="input" id="report-to" type="date" value="${reportTo}"></div><button class="btn" id="export-csv">Export CSV</button></div><section class="stats balance-grid">${summaries.length?summaries.map(x=>`<article class="stat"><div class="stat-label">${x.currency} SPENDING</div><div class="stat-value">${currencyMoney(x.sum,x.currency)}</div><div class="stat-note">${x.count} ${x.count===1?'transaction':'transactions'} · average ${currencyMoney(x.average,x.currency)}</div></article>`).join(''):'<article class="stat"><div class="empty">No expenses in this period.</div></article>'}</section><div class="content-grid"><section class="panel"><div class="panel-head"><h2>Expenses in period</h2></div>${ledgerMarkup(reportRows)}</section><aside class="panel"><div class="panel-head"><h2>Category summary</h2></div>${categoryBreakdown(xs)}</aside></div>`}
function chart(){const n=range==='week'?7:Math.max(1,today.getDate()),days=[];for(let i=n-1;i>=0;i--){const d=new Date(today);d.setDate(d.getDate()-i);days.push(iso(d))}const groups=Object.keys(currencies).map(currency=>{const expenses=userExpenses().filter(e=>e.currency===currency&&days.includes(e.date)),series=Object.keys(categories).map(category=>({category,values:days.map(date=>expenses.filter(e=>e.date===date&&e.category===category).reduce((sum,e)=>sum+Number(e.amount),0))})).filter(x=>x.values.some(Boolean));return{currency,series}}).filter(x=>x.series.length);if(!groups.length)return '<div class="empty">Category trends will appear after expenses are added.</div>';return `<div class="category-trends">${groups.map(({currency,series})=>{const max=Math.max(1,...series.flatMap(x=>x.values)),denominator=Math.max(1,days.length-1);return `<section class="trend-group"><div class="trend-title"><strong>${currency} category trend</strong><span>${range==='week'?'Last 7 days':'This month'}</span></div><svg class="trend-svg" viewBox="0 0 600 180" role="img" aria-label="${currency} spending trend by category"><line x1="20" y1="150" x2="580" y2="150" class="trend-axis"/><line x1="20" y1="90" x2="580" y2="90" class="trend-grid"/><line x1="20" y1="30" x2="580" y2="30" class="trend-grid"/>${series.map(({category,values})=>`<polyline points="${values.map((value,index)=>`${20+index/denominator*560},${150-value/max*120}`).join(' ')}" fill="none" stroke="${categories[category][1]}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><title>${category}: ${currencyMoney(values.reduce((a,b)=>a+b,0),currency)}</title></polyline>`).join('')}</svg><div class="trend-labels"><span>${new Date(days[0]+'T12:00').toLocaleDateString(undefined,{day:'numeric',month:'short'})}</span><span>${new Date(days.at(-1)+'T12:00').toLocaleDateString(undefined,{day:'numeric',month:'short'})}</span></div><div class="trend-legend">${series.map(({category})=>`<span><i style="background:${categories[category][1]}"></i>${escape(category)}</span>`).join('')}</div></section>`}).join('')}</div>`}
function transactions(xs,editable=false){if(!xs.length)return `<div class="empty">No expenses found.</div>`;return xs.map(e=>{const converted=convert(e.amount,e.currency,user().currency);return `<div class="transaction"><div class="cat-icon">${categories[e.category]?.[0]||'◌'}</div><div class="tx-main"><strong>${escape(e.merchant)}</strong><span>${e.category} · ${new Date(e.date+'T12:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}${e.note?' · '+escape(e.note):''}</span></div><div class="amount">−${money(converted)}${e.currency!==user().currency?`<small>${money(e.amount,e.currency)}</small>`:''}${editable?`<button class="row-delete" data-expense-delete="${e.id}">Delete</button>`:''}</div></div>`}).join('')}
function ledgerMarkup(xs,editable=false){if(!xs.length)return '<div class="empty">No transactions found.</div>';return xs.map(x=>`<div class="transaction"><div class="cat-icon">${x.type==='income'?'＋':'−'}</div><div class="tx-main"><strong>${escape(x.description)}</strong><span>${x.type==='income'?'Income':'Expense'} · ${new Date(x.date+'T12:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}${x.note?' · '+escape(x.note):''}</span></div><div class="amount ${x.type}">${x.type==='income'?'+':'−'}${currencyMoney(x.amount,x.currency)}${editable?`<button class="row-delete" data-${x.type}-delete="${x.id}">Delete</button>`:''}</div></div>`).join('')}
function categoryBreakdown(xs){const rows=Object.keys(categories).map(category=>{const amounts={};xs.filter(e=>e.category===category).forEach(e=>amounts[e.currency]=(amounts[e.currency]||0)+Number(e.amount));return{category,amounts,count:Object.keys(amounts).length}}).filter(x=>x.count).sort((a,b)=>b.count-a.count||a.category.localeCompare(b.category));return rows.length?rows.map(({category,amounts})=>`<div class="category"><div class="cat-icon">${categories[category][0]}</div><div><strong>${category}</strong><div class="stat-note">${Object.keys(amounts).length} ${Object.keys(amounts).length===1?'currency':'currencies'}</div></div><div class="category-amount">${Object.entries(amounts).sort(([a],[b])=>a.localeCompare(b)).map(([currency,amount])=>`<div>${currencyMoney(amount,currency)}</div>`).join('')}</div></div>`).join(''):`<div class="empty">Category insights will appear here.</div>`}
function categoryChart(xs){const groups=Object.keys(currencies).map(currency=>{const rows=Object.keys(categories).map(category=>({category,amount:xs.filter(e=>e.currency===currency&&e.category===category).reduce((sum,e)=>sum+Number(e.amount),0)})).filter(x=>x.amount).sort((a,b)=>b.amount-a.amount);return{currency,rows}}).filter(x=>x.rows.length);return groups.length?groups.map(({currency,rows})=>{const max=Math.max(...rows.map(x=>x.amount));return `<section class="category-chart"><div class="category-chart-currency">${currency}</div>${rows.map(({category,amount})=>`<div class="category-chart-row"><div class="category-chart-label"><span>${categories[category][0]} ${escape(category)}</span><strong>${currencyMoney(amount,currency)}</strong></div><div class="category-chart-track"><span style="width:${amount/max*100}%;background:${categories[category][1]}"></span></div></div>`).join('')}</section>`}).join(''):'<div class="empty">Category spending will appear here.</div>'}
function modalMarkup(){if(modal==='expense')return `<div class="modal-backdrop"><form class="modal" id="expense-form"><h2>Add an expense</h2><p class="modal-sub">Record it in the currency you paid. Daybook handles the conversion.</p><div class="form-grid"><div class="field full"><label>MERCHANT OR DESCRIPTION</label><input name="merchant" required autofocus placeholder="e.g. Corner shop"></div><div class="field"><label>AMOUNT</label><input name="amount" required min="0.01" step="0.01" type="number" placeholder="0.00"></div><div class="field"><label>CURRENCY</label><select name="currency">${Object.keys(currencies).map(c=>`<option ${c===user().currency?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>CATEGORY</label><select name="category">${Object.keys(categories).map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field"><label>DATE</label><input name="date" type="date" required value="${iso(today)}"></div><div class="field full"><label>NOTE (OPTIONAL)</label><input name="note" placeholder="What was this for?"></div></div><div class="modal-actions"><button type="button" class="btn" data-action="close">Cancel</button><button class="btn primary">Save expense</button></div></form></div>`;
if(modal==='income')return `<div class="modal-backdrop"><form class="modal" id="income-form"><h2>Add income</h2><p class="modal-sub">Record salary, deposits, refunds or an opening balance in the currency received.</p><div class="form-grid"><div class="field full"><label>SOURCE</label><input name="source" required autofocus placeholder="e.g. Salary"></div><div class="field"><label>AMOUNT</label><input name="amount" required min="0.01" step="0.01" type="number"></div><div class="field"><label>CURRENCY</label><select name="currency">${Object.keys(currencies).map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field"><label>DATE</label><input name="date" type="date" required value="${iso(today)}"></div><div class="field full"><label>NOTE (OPTIONAL)</label><input name="note"></div></div><div class="modal-actions"><button type="button" class="btn" data-action="close">Cancel</button><button class="btn primary">Save income</button></div></form></div>`;
if(modal==='users')return `<div class="modal-backdrop"><div class="modal"><h2>Household profiles</h2><p class="modal-sub">Each person has private expenses, budgets and a preferred currency.</p><div class="users-list">${state.users.map(u=>`<div class="user-option ${u.id===state.activeUser?'active':''}" data-user="${u.id}"><div class="avatar" style="background:${u.color}">${initials(u.name)}</div><div class="user-meta"><strong>${escape(u.name)}</strong><span>${u.email} · ${u.currency}</span></div></div>`).join('')}</div><form id="user-form"><div class="form-grid"><div class="field full"><label>ADD ANOTHER PERSON</label><input name="name" required placeholder="Full name"></div><div class="field"><input name="email" required type="email" placeholder="Email"></div><div class="field"><select name="currency">${Object.keys(currencies).map(c=>`<option>${c}</option>`).join('')}</select></div></div><div class="modal-actions"><button type="button" class="btn" data-action="close">Close</button><button class="btn primary">Add person</button></div></form></div></div>`;return ''}
function bind(){document.querySelectorAll('[data-action="expense"]').forEach(b=>b.onclick=()=>{modal='expense';render()});document.querySelectorAll('[data-action="income"]').forEach(b=>b.onclick=()=>{modal='income';render()});document.querySelectorAll('[data-action="logout"]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/auth/logout',{method:'POST'});state={activeUser:null,users:[],expenses:[],income:[],limits:[],ledger:[]};localStorage.removeItem('daybook-active-user');showAuth(false,'You have signed out.')}catch(err){b.disabled=false;toast(err.message)}});document.querySelectorAll('[data-action="close"]').forEach(b=>b.onclick=()=>{modal=null;render()});document.querySelector('#range')?.addEventListener('change',e=>{range=e.target.value;render()});document.querySelector('#expense-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/expenses',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await loadFinance();modal=null;render();toast('Expense added')}catch(err){toast(err.message)}});document.querySelector('#income-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/income',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await loadFinance();modal=null;render();toast('Income added')}catch(err){toast(err.message)}});document.querySelectorAll('.modal-backdrop').forEach(x=>x.onclick=e=>{if(e.target===x){modal=null;render()}})}
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();const greeting=()=>today.getHours()<12?'morning':today.getHours()<18?'afternoon':'evening';function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.append(el);setTimeout(()=>el.remove(),2600)}
document.addEventListener('click',async e=>{const view=e.target.closest('[data-view]');if(view){activeView=view.dataset.view;render();return}const expense=e.target.closest('[data-expense-delete]'),income=e.target.closest('[data-income-delete]'),del=expense||income;if(del){const type=income?'income':'expense',id=income?income.dataset.incomeDelete:expense.dataset.expenseDelete;if(!confirm(`Delete this ${type} transaction?`))return;try{await api(`/${type==='income'?'income':'expenses'}/`+id,{method:'DELETE'});await loadFinance();render();toast('Transaction deleted')}catch(err){toast(err.message)}return}if(e.target.closest('#export-csv'))exportCsv()});
document.addEventListener('input',e=>{if(e.target.id==='tx-search'){txSearch=e.target.value;document.querySelector('#tx-list').innerHTML=ledgerMarkup(ledgerRows(),true)}});
document.addEventListener('change',e=>{if(e.target.id==='report-from'){reportFrom=e.target.value;render()}if(e.target.id==='report-to'){reportTo=e.target.value;render()}});
document.addEventListener('submit',async e=>{if(e.target.id!=='limit-form')return;e.preventDefault();const f=new FormData(e.target),currency=f.get('currency');try{await api('/budget-limits/'+currency,{method:'PUT',body:JSON.stringify({monthlyLimit:Number(f.get('monthlyLimit'))})});state.limits=await api('/budget-limits');render();toast('Monthly limit saved')}catch(err){toast(err.message)}});
function exportCsv(){const xs=userExpenses().filter(e=>e.date>=reportFrom&&e.date<=reportTo),q=v=>'"'+String(v??'').replaceAll('"','""')+'"',rows=[['Date','Merchant','Category','Amount','Currency','Note'],...xs.map(e=>[e.date,e.merchant,e.category,e.amount,e.currency,e.note||''])],blob=new Blob([rows.map(r=>r.map(q).join(',')).join('\n')],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`daybook-${reportFrom}-${reportTo}.csv`;a.click();URL.revokeObjectURL(url)}
function showAuth(register=false,message=''){document.querySelector('#app').innerHTML=`<div class="modal-backdrop" style="position:fixed"><form class="modal" id="auth-form"><div class="brand"><span class="brand-mark">↗</span>daybook</div><h2>${register?'Create your account':'Welcome back'}</h2><p class="modal-sub">${register?'Use the private registration code supplied by the household administrator.':'Sign in to access your private finances.'}</p>${message?`<div class="empty">${escape(message)}</div>`:''}<div class="form-grid">${register?'<div class="field full"><label>NAME</label><input name="name" required autocomplete="name"></div>':''}<div class="field full"><label>EMAIL</label><input name="email" type="email" required autocomplete="email"></div><div class="field full"><label>PASSWORD</label><input name="password" type="password" minlength="12" required autocomplete="${register?'new-password':'current-password'}"></div>${register?`<div class="field"><label>CURRENCY</label><select name="currency">${Object.keys(currencies).map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field"><label>REGISTRATION CODE</label><input name="registrationCode" type="password" required autocomplete="off"></div>`:''}</div><div class="modal-actions"><button type="button" class="btn" id="auth-toggle">${register?'Sign in instead':'Create account'}</button><button class="btn primary">${register?'Create account':'Sign in'}</button></div></form></div>`;document.querySelector('#auth-toggle').onclick=()=>showAuth(!register);document.querySelector('#auth-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),body=Object.fromEntries(f);try{const me=await api(register?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify(body)});state.users=[me];state.activeUser=me.id;await loadFinance();render()}catch(err){showAuth(register,err.message)}}}
async function loadFinance(){[state.expenses,state.income,state.limits,state.ledger]=await Promise.all([api('/expenses'),api('/income'),api('/budget-limits'),api('/transactions')])}
async function bootstrap(){document.querySelector('#app').innerHTML='<div class="empty" style="padding-top:20vh">Loading Daybook…</div>';try{const me=await api('/me');state.users=[me];state.activeUser=me.id;await loadFinance();render()}catch(err){if(err.status===401)return showAuth();document.querySelector('#app').innerHTML=`<div class="empty" style="padding-top:20vh"><b>Could not connect to Daybook.</b><br><br>${escape(err.message)}</div>`}}bootstrap();
