import 'dotenv/config';
import express from 'express';
import mysql from 'mysql2/promise';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const app=express();
const port=Number(process.env.PORT||3000);
const production=process.env.NODE_ENV==='production';
const pool=mysql.createPool({host:process.env.DB_HOST||'localhost',port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||'root',password:process.env.DB_PASSWORD||'',database:process.env.DB_NAME||'daybook',waitForConnections:true,connectionLimit:Number(process.env.DB_POOL_SIZE||10),decimalNumbers:true,dateStrings:true});
const currencies=new Set(['GBP','USD','EUR','INR','JPY','CAD','AUD','GEL']);
const categories=new Set(['Groceries','Dining Out','House Rent','Electricity Bill','Mobile Bill','Internet Bill','Cab Charges','Bus Ticket','Train Ticket','Shopping','Health','Insurance','Personal Care','Subscriptions','Entertainment','Travel','Gifts & Donations','Taxes','Hand Loan','Debt Payments','Fees & Charges','Food','Other']);
const clean=s=>typeof s==='string'?s.trim():'';
const validId=id=>/^[0-9a-f-]{36}$/i.test(id||'');
const sessionDays=30;
const loginAttempts=new Map();

app.use(express.json({limit:'32kb'}));

const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2));
const tokenHash=token=>crypto.createHash('sha256').update(token).digest('hex');
const safeEqual=(a,b)=>{const left=Buffer.from(String(a)),right=Buffer.from(String(b));return left.length===right.length&&crypto.timingSafeEqual(left,right)};
const passwordHash=password=>{const salt=crypto.randomBytes(16).toString('hex');return `scrypt$${salt}$${crypto.scryptSync(password,salt,64).toString('hex')}`};
const passwordMatches=(password,stored)=>{try{const [algorithm,salt,expected]=stored.split('$');if(algorithm!=='scrypt'||!salt||!expected)return false;const actual=crypto.scryptSync(password,salt,64);return crypto.timingSafeEqual(actual,Buffer.from(expected,'hex'))}catch{return false}};
const publicUser=row=>({id:row.id,name:row.name,email:row.email,currency:row.currency,budget:row.budget,color:row.color});
const setSessionCookie=(res,token,maxAge=sessionDays*86400)=>res.setHeader('Set-Cookie',`daybook_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${production?'; Secure':''}`);
const createSession=async(res,userId)=>{const token=crypto.randomBytes(32).toString('base64url');await pool.execute('INSERT INTO sessions (id,user_id,token_hash,expires_at) VALUES (?,?,?,DATE_ADD(NOW(),INTERVAL ? DAY))',[crypto.randomUUID(),userId,tokenHash(token),sessionDays]);setSessionCookie(res,token)};
const requireAuth=async(req,res,next)=>{try{const token=cookies(req).daybook_session;if(!token)return res.status(401).json({error:'Authentication required.'});const [rows]=await pool.execute('SELECT u.id,u.name,u.email,u.currency,u.monthly_budget AS budget,u.color,s.id AS session_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>NOW() LIMIT 1',[tokenHash(token)]);if(!rows.length){setSessionCookie(res,'',0);return res.status(401).json({error:'Session expired. Please sign in again.'})}req.user=rows[0];next()}catch(e){next(e)}};
const rateLimited=req=>{const key=req.ip;const now=Date.now(),recent=(loginAttempts.get(key)||[]).filter(t=>now-t<15*60_000);recent.push(now);loginAttempts.set(key,recent);return recent.length>10};

app.get('/api/health',async(_req,res,next)=>{try{await pool.query('SELECT 1');res.json({status:'ok',database:'connected'})}catch(e){next(e)}});
app.post('/api/auth/register',async(req,res,next)=>{try{if(rateLimited(req))return res.status(429).json({error:'Too many attempts. Try again later.'});const name=clean(req.body.name),email=clean(req.body.email).toLowerCase(),password=String(req.body.password||''),currency=clean(req.body.currency).toUpperCase(),code=String(req.body.registrationCode||'');if(!process.env.REGISTRATION_CODE)return res.status(503).json({error:'Account registration is not configured.'});if(!safeEqual(code,process.env.REGISTRATION_CODE))return res.status(403).json({error:'Invalid registration code.'});if(!name||!/^\S+@\S+\.\S+$/.test(email)||password.length<12||!currencies.has(currency))return res.status(400).json({error:'Name, valid email, 12+ character password and currency are required.'});const hash=passwordHash(password);const [existing]=await pool.execute('SELECT id,password_hash FROM users WHERE email=? LIMIT 1',[email]);let userId;if(existing.length){if(existing[0].password_hash)return res.status(409).json({error:'That email address already has an account.'});userId=existing[0].id;await pool.execute('UPDATE users SET name=?,password_hash=?,currency=? WHERE id=?',[name,hash,currency,userId])}else{userId=crypto.randomUUID();await pool.execute('INSERT INTO users (id,name,email,password_hash,currency,monthly_budget,color) VALUES (?,?,?,?,?,?,?)',[userId,name,email,hash,currency,0,'#1d654f'])}await createSession(res,userId);const [rows]=await pool.execute('SELECT id,name,email,currency,monthly_budget AS budget,color FROM users WHERE id=?',[userId]);res.status(201).json(publicUser(rows[0]))}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{if(rateLimited(req))return res.status(429).json({error:'Too many attempts. Try again later.'});const email=clean(req.body.email).toLowerCase(),password=String(req.body.password||'');const [rows]=await pool.execute('SELECT id,name,email,password_hash,currency,monthly_budget AS budget,color FROM users WHERE email=? LIMIT 1',[email]);if(!rows.length||!rows[0].password_hash||!passwordMatches(password,rows[0].password_hash))return res.status(401).json({error:'Invalid email or password.'});await createSession(res,rows[0].id);res.json(publicUser(rows[0]))}catch(e){next(e)}});
app.post('/api/auth/logout',requireAuth,async(req,res,next)=>{try{await pool.execute('DELETE FROM sessions WHERE id=?',[req.user.session_id]);setSessionCookie(res,'',0);res.status(204).end()}catch(e){next(e)}});
app.get('/api/me',requireAuth,(req,res)=>res.json(publicUser(req.user)));
app.patch('/api/me',requireAuth,async(req,res,next)=>{try{const budget=Number(req.body.budget),currency=clean(req.body.currency).toUpperCase();if(!(budget>=0)||!currencies.has(currency))return res.status(400).json({error:'Valid budget and currency are required.'});await pool.execute('UPDATE users SET monthly_budget=?,currency=? WHERE id=?',[budget,currency,req.user.id]);res.json({budget,currency})}catch(e){next(e)}});
app.get('/api/expenses',requireAuth,async(req,res,next)=>{try{const [rows]=await pool.execute('SELECT id,user_id AS userId,merchant,amount,currency,category,expense_date AS date,note FROM expenses WHERE user_id=? ORDER BY expense_date DESC,created_at DESC',[req.user.id]);res.json(rows)}catch(e){next(e)}});
app.post('/api/expenses',requireAuth,async(req,res,next)=>{try{const merchant=clean(req.body.merchant),currency=clean(req.body.currency).toUpperCase(),category=clean(req.body.category),date=clean(req.body.date),note=clean(req.body.note)||null,amount=Number(req.body.amount);if(!merchant||!(amount>0)||!currencies.has(currency)||!categories.has(category)||!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({error:'Invalid expense data.'});const row={id:crypto.randomUUID(),userId:req.user.id,merchant,amount,currency,category,date,note};await pool.execute('INSERT INTO expenses (id,user_id,merchant,amount,currency,category,expense_date,note) VALUES (?,?,?,?,?,?,?,?)',[row.id,row.userId,merchant,amount,currency,category,date,note]);res.status(201).json(row)}catch(e){next(e)}});
app.delete('/api/expenses/:id',requireAuth,async(req,res,next)=>{try{if(!validId(req.params.id))return res.status(400).json({error:'Invalid expense id.'});const [result]=await pool.execute('DELETE FROM expenses WHERE id=? AND user_id=?',[req.params.id,req.user.id]);if(!result.affectedRows)return res.status(404).json({error:'Expense not found.'});res.status(204).end()}catch(e){next(e)}});
app.get('/api/income',requireAuth,async(req,res,next)=>{try{const [rows]=await pool.execute('SELECT id,user_id AS userId,source,amount,currency,income_date AS date,note FROM income_transactions WHERE user_id=? ORDER BY income_date DESC,created_at DESC',[req.user.id]);res.json(rows)}catch(e){next(e)}});
app.post('/api/income',requireAuth,async(req,res,next)=>{try{const source=clean(req.body.source),currency=clean(req.body.currency).toUpperCase(),date=clean(req.body.date),note=clean(req.body.note)||null,amount=Number(req.body.amount);if(!source||!(amount>0)||!currencies.has(currency)||!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({error:'Valid income source, amount, currency and date are required.'});const row={id:crypto.randomUUID(),userId:req.user.id,source,amount,currency,date,note};await pool.execute('INSERT INTO income_transactions (id,user_id,source,amount,currency,income_date,note) VALUES (?,?,?,?,?,?,?)',[row.id,row.userId,source,amount,currency,date,note]);res.status(201).json(row)}catch(e){next(e)}});
app.delete('/api/income/:id',requireAuth,async(req,res,next)=>{try{if(!validId(req.params.id))return res.status(400).json({error:'Invalid income id.'});const [result]=await pool.execute('DELETE FROM income_transactions WHERE id=? AND user_id=?',[req.params.id,req.user.id]);if(!result.affectedRows)return res.status(404).json({error:'Income transaction not found.'});res.status(204).end()}catch(e){next(e)}});
app.get('/api/budget-limits',requireAuth,async(req,res,next)=>{try{const [rows]=await pool.execute('SELECT currency,monthly_limit AS monthlyLimit FROM budget_limits WHERE user_id=? ORDER BY currency',[req.user.id]);res.json(rows)}catch(e){next(e)}});
app.put('/api/budget-limits/:currency',requireAuth,async(req,res,next)=>{try{const currency=clean(req.params.currency).toUpperCase(),monthlyLimit=Number(req.body.monthlyLimit);if(!currencies.has(currency)||!(monthlyLimit>=0))return res.status(400).json({error:'Valid currency and monthly limit are required.'});await pool.execute('INSERT INTO budget_limits (user_id,currency,monthly_limit) VALUES (?,?,?) ON DUPLICATE KEY UPDATE monthly_limit=VALUES(monthly_limit)',[req.user.id,currency,monthlyLimit]);res.json({currency,monthlyLimit})}catch(e){next(e)}});
app.get('/api/transactions',requireAuth,async(req,res,next)=>{try{const [rows]=await pool.execute(`SELECT id,'income' AS type,source AS description,amount,currency,income_date AS date,note,created_at FROM income_transactions WHERE user_id=? UNION ALL SELECT id,'expense' AS type,merchant AS description,amount,currency,expense_date AS date,note,created_at FROM expenses WHERE user_id=? ORDER BY date DESC,created_at DESC`,[req.user.id,req.user.id]);res.json(rows)}catch(e){next(e)}});

const root=path.dirname(fileURLToPath(import.meta.url));app.use(express.static(root));app.get('*',(_req,res)=>res.sendFile(path.join(root,'index.html')));
app.use((err,_req,res,_next)=>{console.error(err);if(err.code==='ER_DUP_ENTRY')return res.status(409).json({error:'That email address already exists.'});if(err.code==='ER_NO_SUCH_TABLE'||err.code==='ER_BAD_DB_ERROR'||err.code==='ECONNREFUSED')return res.status(503).json({error:'Database unavailable. Apply the database migrations and check environment settings.'});res.status(500).json({error:'Unexpected server error.'})});
app.listen(port,()=>console.log(`Daybook running at http://localhost:${port}`));
